---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: email
  name: email
spec:
  containers:
  - image: localhost/postfix:latest
    name: email-postfix
    ports:
    - containerPort: 143
      hostPort: 143
    - containerPort: 465
      hostPort: 465
    - containerPort: 587
      hostPort: 587
    - containerPort: 993
      hostPort: 993
    - containerPort: 25
      hostPort: 2525
    - containerPort: 4190
      hostPort: 4190
    volumeMounts:
    - mountPath: /dev/log
      name: dev-log
    - mountPath: /run/postfix/socket
      name: socket
    - mountPath: /etc/postfix/ca.pem
      name: CA.pem
    - mountPath: /etc/postfix/cert.pem
      name: fullchain.pem
    - mountPath: /etc/postfix/key.pem
      name: privkey.pem
    - mountPath: /etc/postfix/main.cf
      name: postfix-main.cf
    - mountPath: /etc/postfix/master.cf
      name: postfix-master.cf
    - mountPath: /etc/postfix/relay.lmdb
      name: postfix-relay.lmdb
    - mountPath: /etc/postfix/relay_recipient.lmdb
      name: postfix-relay_recipient.lmdb
    - mountPath: /etc/postfix/recipient_canonical.lmdb
      name: postfix-recipient_canonical.lmdb
    - mountPath: /etc/postfix/sender_relay.lmdb
      name: postfix-sender_relay.lmdb
    - mountPath: /etc/postfix/transport.lmdb
      name: postfix-transport.lmdb
    - mountPath: /etc/sasl2/smtpd.conf
      name: postfix-smtpd.conf
  - image: localhost/ldap:latest
    name: email-openldap
    volumeMounts:
    - mountPath: /dev/log
      name: dev-log
    - mountPath: /run/slapd/socket
      name: socket
    - mountPath: /etc/openldap/ca.pem
      name: CA.pem
    - mountPath: /etc/openldap/cert.pem
      name: fullchain.pem
    - mountPath: /etc/openldap/key.pem
      name: privkey.pem
    - mountPath: /etc/openldap/slapd.conf
      name: ldap-slapd.conf
    - mountPath: /var/lib/ldap
      name: ldap-lib
  - image: localhost/cyrus:latest
    name: email-cyrusimapd
    volumeMounts:
    - mountPath: /dev/log
      name: dev-log
    - mountPath: /run/cyrus/socket
      name: socket
    - mountPath: /etc/ca.pem
      name: CA.pem
    - mountPath: /etc/cert.pem
      name: fullchain.pem
    - mountPath: /etc/key.pem
      name: privkey.pem
    - mountPath: /etc/cyrus.conf
      name: cyrus-cyrus.conf
    - mountPath: /etc/imapd.conf
      name: cyrus-imapd.conf
    - mountPath: /run/cyrus
      name: cyrus-run
    - mountPath: /var/lib/cyrus
      name: cyrus-lib
    - mountPath: /var/spool/sieve
      name: cyrus-sieve
    - mountPath: /var/spool/cyrus/mail
      name: cyrus-spool
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /con/socket
      type: Directory
    name: socket
  - hostPath:
      path: /dev/log
      type: File
    name: dev-log
  - hostPath:
      path: /etc/CA.pem
      type: File
    name: CA.pem
  - hostPath:
      path: /etc/fullchain.pem
      type: File
    name: fullchain.pem
  - hostPath:
      path: /etc/privkey.pem
      type: File
    name: privkey.pem
  - hostPath:
      path: /con/ldap/slapd.conf
      type: File
    name: ldap-slapd.conf
  - hostPath:
      path: /con/ldap/lib
      type: Directory
    name: ldap-lib
  - hostPath:
      path: /con/postfix/relay_recipient.lmdb
      type: File
    name: postfix-relay_recipient.lmdb
  - hostPath:
      path: /con/postfix/sender_relay.lmdb
      type: File
    name: postfix-sender_relay.lmdb
  - hostPath:
      path: /con/postfix/main.cf
      type: File
    name: postfix-main.cf
  - hostPath:
      path: /con/postfix/recipient_canonical.lmdb
      type: File
    name: postfix-recipient_canonical.lmdb
  - hostPath:
      path: /con/postfix/transport.lmdb
      type: File
    name: postfix-transport.lmdb
  - hostPath:
      path: /con/postfix/smtpd.conf
      type: File
    name: postfix-smtpd.conf
  - hostPath:
      path: /con/postfix/master.cf
      type: File
    name: postfix-master.cf
  - hostPath:
      path: /con/postfix/relay.lmdb
      type: File
    name: postfix-relay.lmdb
  - hostPath:
      path: /con/cyrus/lib
      type: Directory
    name: cyrus-lib
  - hostPath:
      path: /con/cyrus/run
      type: Directory
    name: cyrus-run
  - hostPath:
      path: /con/cyrus/cyrus.conf
      type: File
    name: cyrus-cyrus.conf
  - hostPath:
      path: /con/cyrus/imapd.conf
      type: File
    name: cyrus-imapd.conf
  - hostPath:
      path: /con/cyrus/sieve
      type: Directory
    name: cyrus-sieve
  - hostPath:
      path: /con/cyrus/spool
      type: Directory
    name: cyrus-spool
