---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: email
  name: email
spec:
  containers:
  - image: localhost/postfix:latest
    name: postfix
    ports:
    - containerPort: 465
      hostPort: 465
    - containerPort: 587
      hostPort: 587
    - containerPort: 25
      hostPort: 2525
    volumeMounts:
    - mountPath: /dev/log
      name: dev_log
    - mountPath: /run/postfix/socket
      name: sockets
    - mountPath: /etc/postfix/ca.pem
      name: ca_crt
    - mountPath: /etc/postfix/cert.pem
      name: cert
    - mountPath: /etc/postfix/key.pem
      name: key
    - mountPath: /etc/postfix/main.cf
      name: main_cf
    - mountPath: /etc/postfix/master.cf
      name: master_cf
    - mountPath: /etc/postfix/relay.lmdb
      name: relay_lmdb
    - mountPath: /etc/postfix/relay_recipient.lmdb
      name: relay_recipient_lmdb
    - mountPath: /etc/postfix/recipient_canonical.lmdb
      name: recipient_canonical_lmdb
    - mountPath: /etc/postfix/sender_relay.lmdb
      name: sender_relay_lmdb
    - mountPath: /etc/postfix/transport.lmdb
      name: transport_lmdb
    - mountPath: /etc/sasl2/smtpd.conf
      name: smtpd_conf
  - image: localhost/ldap:latest
    name: openldap
    volumeMounts:
    - mountPath: /dev/log
      name: dev_log
    - mountPath: /run/slapd/socket
      name: sockets
    - mountPath: /etc/openldap/ca.pem
      name: ca_crt
    - mountPath: /etc/openldap/cert.pem
      name: cert
    - mountPath: /etc/openldap/key.pem
      name: key
    - mountPath: /etc/openldap/slapd.conf
      name: slapd_conf
    - mountPath: /var/lib/ldap
      name: slapd_lib
  - image: localhost/cyrus:latest
    name: cyrus_imapd
    ports:
    - containerPort: 143
      hostPort: 143
    - containerPort: 993
      hostPort: 993
    - containerPort: 2003
      hostPort: 2003
    - containerPort: 4190
      hostPort: 4190
    volumeMounts:
    - mountPath: /dev/log
      name: dev_log
    - mountPath: /run/cyrus/socket
      name: sockets
    - mountPath: /etc/ca.pem
      name: ca_crt
    - mountPath: /etc/cert.pem
      name: cert
    - mountPath: /etc/key.pem
      name: key
    - mountPath: /etc/cyrus.conf
      name: cyrus_conf
    - mountPath: /etc/imapd.conf
      name: imapd_conf
    - mountPath: /run/cyrus
      name: cyrus_run
    - mountPath: /var/lib/cyrus
      name: cyrus_lib
    - mountPath: /var/spool/sieve
      name: cyrus_sieve
    - mountPath: /var/spool/cyrus/mail
      name: cyrus_spool
  restartPolicy: always
  volumes:
  - hostPath:
      path: /dev/log
      type: Socket
    name: dev_log
  - hostPath:
      path: /containers/sockets
      type: Directory
    name: sockets
  - hostPath:
      path: /etc/CA.pem
      type: File
    name: ca_crt
  - hostPath:
      path: /etc/fullchain.pem
      type: File
    name: cert
  - hostPath:
      path: /etc/privkey.pem
      type: File
    name: key
  - hostPath:
      path: /containers/postfix/main.cf
      type: File
    name: main_cf
  - hostPath:
      path: /containers/postfix/master.cf
      type: File
    name: master_cf
  - hostPath:
      path: /containers/postfix/smtpd.conf
      type: File
    name: smtpd_conf
  - hostPath:
      path: /containers/postfix/relay.lmdb
      type: File
    name: relay_lmdb
  - hostPath:
      path: /containers/postfix/relay_recipient.lmdb
      type: File
    name: relay_recipient_lmdb
  - hostPath:
      path: /containers/postfix/recipient_canonical.lmdb
      type: File
    name: recipient_canonical_lmdb
  - hostPath:
      path: /containers/postfix/sender_relay.lmdb
      type: File
    name: sender_relay_lmdb
  - hostPath:
      path: /containers/postfix/transport.lmdb
      type: File
    name: transport_lmdb
  - hostPath:
      path: /containers/ldap/slapd.conf
      type: File
    name: slapd_conf
  - hostPath:
      path: /containers/ldap/lib
      type: Directory
    name: slapd_lib
  - hostPath:
      path: /containers/cyrus/cyrus.conf
      type: File
    name: cyrus_conf
  - hostPath:
      path: /containers/cyrus/imapd.conf
      type: File
    name: imapd_conf
  - hostPath:
      path: /containers/cyrus/lib
      type: Directory
    name: cyrus_lib
  - hostPath:
      path: /containers/cyrus/run
      type: Directory
    name: cyrus_run
  - hostPath:
      path: /containers/cyrus/sieve
      type: Directory
    name: cyrus_sieve
  - hostPath:
      path: /containers/cyrus/spool
      type: Directory
    name: cyrus_spool
